name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ '1.8', '11', '12' ]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Cache m2 repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Install dependencies
      run: lein deps
    - name: Run lein check
      if: matrix.java == '11'
      run: >-
        ! lein check 2>&1 > /dev/null |
        grep cljam |
        sed -E 's/^Reflection warning, ([^:]+):([0-9]+):([0-9]+) - (.*)$/::warning file=\1,line=\2,col=\3::\4/' |
        grep '::warning'
    - name: Run tests
      run: |
        lein with-profile +dev:+1.8:+1.9 test
        lein with-profile dev bin
        target/cljam version

  ea-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Download Early-Access Builds
      run: curl -sSL https://jdk.java.net/14 | grep -m1 -Eo 'https.*linux-x64_bin.tar.gz' | xargs curl -O
    - name: Get name of the downloaded jdkFile
      run: echo -e "::set-env name=JDKFILE::$(find . -name '*linux-x64_bin.tar.gz' | head -n1)"
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ea
        jdkFile: ${{ env.JDKFILE }}
        architecture: x64
    - name: Cache m2 repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Install Dependencies
      run: lein deps
    - name: Run tests
      run: |
        lein with-profile +dev:+1.8:+1.9 test
        lein with-profile dev bin
        target/cljam version

  deploy:
    needs: [build, ea-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        architecture: x64
    - name: Deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: ./deploy-snapshot.sh
